### ISSUE TITLE
Add support for Ubuntu 22.04 as soon as Puppet supports it

### ISSUE THREAD

**Issue by mlegner** [siemens/puppet-pam_pkcs11#6]
Some discussion took place at https://github.com/siemens/puppet-pam_pkcs11/pull/3#discussion_r931907779.

See also:
- https://tickets.puppetlabs.com/browse/PA-4233 (closed)
- https://tickets.puppetlabs.com/browse/SERVER-3193 (open)
- https://tickets.puppetlabs.com/browse/PDB-5523 (open)

For the Ruby dependencies, see
- https://tickets.puppetlabs.com/browse/MODULES-11161
- https://github.com/puppetlabs/puppet-module-gems/issues/166

**Comment by cmhe** [comment]
The ubuntu puppet repo currently only contains `puppet-agent` packages:

- http://apt.puppetlabs.com/dists/jammy/index.html

We will also need the ruby 3 ports of the dependent puppet modules:

- https://rubygems.org/search?query=puppet-module-posix-default
- https://rubygems.org/search?query=puppet-module-posix-dev

Since ruby 3 is the default version of Ubuntu 22.04.

**Comment by cmhe** [comment]
Points to keep in mind when adding Ubuntu 22.04 support:
  - `mapper_module_dir` is the same as in Debian 11 ([link](https://github.com/siemens/puppet-pam_pkcs11/pull/15#pullrequestreview-1078572578))
